webhooks:
- name: PR_REVIEWS
  url: https://chat.googleapis.com/v1/spaces/AAAAW_3e4mI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=UUl0fN2gbs2lVVt6e_msZ6-lxdbV7PKT6nvcanA8iRI
  description: SRE PR Review channel
- name: AUGER
  url: https://chat.googleapis.com/v1/spaces/AAQARo5bx6M/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=924HvChd_uiRXsn2ab5sEXNViH3KsThJPCDNIJCG_lo
  description: Drill Down with Auger AI
- name: AUGER_POC
  url: https://chat.googleapis.com/v1/spaces/AAQACu5esbQ/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=D7uPQLzLuBRZruzrlwusDar_HYsUpMcI9BZrp6dJ4q8
  description: Auger POC Channel
- name: SRE
  url: https://chat.googleapis.com/v1/spaces/AAAAi3KmSsE/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=IlrOdXjX7v0Zkt6HkDDtc_Ec9_N-J0vbe8MpSO4-eOU
  description: SRE Internal Channel
- name: PRISMA_INTERNAL
  url: https://chat.googleapis.com/v1/spaces/AAQAyXQryaI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=RiBNQn_UxXpJZE79hDoNic8pBEpGaEex6BhJ5FZxIxY
  description: Prisma Jira CVE process for task 174
